include("../src/t001_introduction.jl")
include("../src/t002_data_ingestion.jl")
include("../src/t003_flux_intro.jl")
include("../src/t004_conv_layers.jl")
include("../src/t005_recurrent_layers.jl")
include("../src/t006_optimization.jl")
include("../src/t007_conclusion.jl")
